---
- name: Register server
  hosts: localhost
  connection: local
  tasks:
    - name: Getting Public IP
      azure_rm_publicipaddress_facts:
        resource_group: "{{ resource_group }}"
        name: '{{ vm_public_ip_name }}'
      register: pip_output

    - name: Adding public IP to hosts
      add_host:
        hostname: "{{ pip_output.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
        ansible_user: "{{ admin_username }}"
        groups: awx
        
- name: Install AWX Software
  hosts: awx
  gather_facts: no
  become: true
  tasks:
    - name: Install AWX
      shell: ansible-playbook -i inventory install.yml
      args:
        chdir: '/home/{{ admin_username }}/awx/installer/'
      
    - name: Wait for AWX database migration to complete
      pause:
        minutes: 5