trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CopyFiles@2
  displayName: 'Copy Ansible files to artifacts'
  inputs:
    SourceFolder:
    Contents: |
     **/*.yml
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

